name: itvlist

on:
  schedule:
    - cron: '0 21 5 * *'   # 每月5日 21:00 UTC 自动运行
  push:
    branches:
      - main
  workflow_dispatch:        # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: pip install selenium requests futures eventlet aiohttp aiofiles asyncio

      - name: Run cctv
        run: python ${{ github.workspace }}/new.py

      - name: 提交更改
        run: |
          git config --local user.email "ssili@126.com"
          git config --local user.name "ssili126"
          git add .
          git commit *.txt -m "Add generated file"
          #git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
