name: itvlist

on:
  schedule:
    - cron: '0 21 5 * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: pip install selenium requests futures eventlet aiohttp aiofiles asyncio

      - name: Run cctv
        run: python ${{ github.workspace }}/new.py

      - name: List generated .txt files
        run: ls -l *.txt || echo "No .txt files found"

      - name: 提交更改
        run: |
          git config --local user.email "ssili@126.com"
          git config --local user.name "ssili126"
          git add *.txt || echo "No .txt files to add"
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Add generated file"
          git push -f
